In [1]:
import sys 
sys.path.append("..") 

import os
os.getcwd() 
os.environ["TOKENIZERS_PARALLELISM"] = "false"
import warnings
from test import *
warnings.filterwarnings("ignore")
from datasets import load_dataset,load_metric
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
import torch_optimizer as optim
from transformers.optimization import Adafactor, AdafactorSchedule
import torch.backends.cudnn as cudnn
from utils import *
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler, SubsetRandomSampler
from torch.autograd import Variable
import logging
import sys
import transformers
from basic_model import *
import time
import argparse
from tqdm import tqdm
import string
from cycle import *
from train import *
from parameter import *
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
from utils import *

2022-05-30 15:52:27 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX


In [6]:

GABpretrained  =  AutoModelForSeq2SeqLM.from_pretrained('t5-small')

In [10]:
a = en('translate English to German: India and Japan prime ministers meet in Tokyo')[0]
a = en('translate English to German: India and Japan prime ministers meet in Tokyo')[0]
A = torch.vstack((a,a))

In [13]:
A[0]= 0
A

tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [13959,  1566,    12,  2968,    10,  1547,    11,  3411,  3427,  6323,
             7,   942,    16, 12653,     1]])

In [14]:
b = GABpretrained.generate(input_ids = A, num_beams = 4, early_stopping = True, max_length = 512, length_penalty =0.6, repetition_penalty = 1, num_return_sequences=4) #do_sample =True )
b

tensor([[    0,     0,     0,  ...,     0,     0,     0],
        [    0,     0,     0,  ...,     0,     0,     0],
        [    0,     0,     0,  ...,     0,     0,     0],
        ...,
        [    0, 10194,    35,  ...,     0,     0,     0],
        [    0,    86,   304,  ...,     0,     0,     0],
        [    0,    86,   304,  ...,     0,     0,     0]])

In [ ]:

db = d(b)
db

['Die Premierminister Indiens und Japans treffen sich in Tokio',
 'Indien und Japans Premierminister treffen sich in Tokio',
 'In Tokio treffen sich die Premierminister Indiens und Japans',
 'In Tokio treffen sich Premierminister Indiens und Japans']

In [17]:
a = torch.rand((2,3))
a

tensor([[0.3681, 0.3056, 0.2795],
        [0.2787, 0.5155, 0.8449]])

In [20]:
torch.repeat_interleave(a, repeats=3, dim=0) 

tensor([[0.3681, 0.3056, 0.2795],
        [0.3681, 0.3056, 0.2795],
        [0.3681, 0.3056, 0.2795],
        [0.2787, 0.5155, 0.8449],
        [0.2787, 0.5155, 0.8449],
        [0.2787, 0.5155, 0.8449]])

In [21]:
tile(a,0,3)

tensor([[0.3681, 0.3056, 0.2795],
        [0.3681, 0.3056, 0.2795],
        [0.3681, 0.3056, 0.2795],
        [0.2787, 0.5155, 0.8449],
        [0.2787, 0.5155, 0.8449],
        [0.2787, 0.5155, 0.8449]])