In [36]:
import torch
import torch.nn.functional as F
logits = torch.randn(3, 4)*10
print(logits)


tensor([[ 6.6839,  3.2299, -6.6587, 14.3229],
        [-6.2666,  1.7300, -1.6980,  9.7503],
        [ 7.1638,  1.0115,  4.6089, -8.4124]])


In [39]:
a = torch.Tensor([[[-18.2558,  -9.6608, -15.5738,    -50.0866, -50.1331, -50.2364],
         [-17.0320,  -5.4464,  -8.3393, -31.7471, -31.7737, -31.9135],
         [-43.6341, -22.0459, -23.3187,    -64.4549, -64.7413, -64.8144],
          
         [-37.4918, -20.9379, -18.5400,    -55.9991, -55.9780, -56.0689],
         [-22.0452,  -9.2300,  -8.3841,    -40.1369, -40.0837, -40.0113],
         [-41.9367, -20.4680, -21.2568,    -66.0529, -65.9898, -66.0962]],

        [[-15.4946, -10.1611, -16.0635,    -48.1857, -48.2550, -48.2414],
         [-22.2560, -10.2582, -13.8651,    -42.1722, -42.1927, -42.2060],
         [-22.9107,  -6.6016,  -8.0379,    -37.7596, -37.7748, -37.6419],
          
         [-32.9230, -14.5505, -16.7494,    -51.3574, -51.4561, -51.5225],
         [-41.2204, -25.1509, -16.1806,    -62.8647, -63.0306, -62.8994],
         [-51.8093, -30.5719, -26.5000,    -72.4618, -72.6369, -72.5331]],

        [[-12.7670,  -5.9766, -12.2441,    -37.2750, -37.2353, -37.2623],
         [-18.7271,  -9.5906, -12.4751,    -37.9014, -37.8288, -37.8236],
         [-23.1169, -13.8109,  -4.2865,    -40.0670, -40.1864, -40.0178],
          
         [-55.5245, -27.0762, -26.6836,    -70.3255, -70.3861, -70.4303],
         [-30.0465, -18.9549, -17.3846,    -57.4578, -57.4611, -57.3958],
         [-28.7090, -12.5783, -16.4133,    -52.9247, -52.9540, -52.8771]]])

In [44]:
import numpy as np
pow(np.e,a)

tensor([[[1.1793e-08, 6.3734e-05, 1.7234e-07, 1.7687e-22, 1.6884e-22,
          1.5227e-22],
         [4.0096e-08, 4.3118e-03, 2.3894e-04, 1.6308e-14, 1.5880e-14,
          1.3808e-14],
         [1.1219e-19, 2.6643e-10, 7.4613e-11, 1.0176e-28, 7.6421e-29,
          7.1034e-29],
         [5.2182e-17, 8.0684e-10, 8.8752e-09, 4.7852e-25, 4.8872e-25,
          4.4626e-25],
         [2.6662e-10, 9.8053e-05, 2.2847e-04, 3.7048e-18, 3.9073e-18,
          4.2006e-18],
         [6.1252e-19, 1.2908e-09, 5.8653e-10, 2.0587e-29, 2.1928e-29,
          1.9715e-29]],

        [[1.8654e-07, 3.8645e-05, 1.0561e-07, 1.1836e-21, 1.1044e-21,
          1.1195e-21],
         [2.1594e-10, 3.5069e-05, 9.5162e-07, 4.8400e-19, 4.7418e-19,
          4.6792e-19],
         [1.1220e-10, 1.3582e-03, 3.2299e-04, 3.9922e-17, 3.9320e-17,
          4.4909e-17],
         [5.0318e-15, 4.7951e-07, 5.3190e-08, 4.9632e-23, 4.4968e-23,
          4.2079e-23],
         [1.2537e-18, 1.1943e-11, 9.3941e-08, 4.9912e-28, 4.2282e-28

In [45]:
# Sample soft categorical using reparametrization trick:
soft = F.gumbel_softmax(a, tau=1, hard=False,dim=-1)
print(soft)
# Sample hard categorical using "Straight-through" trick:
soft = F.gumbel_softmax(a, tau=100, hard=True,dim=-1)
print(soft)

tensor([[[9.5947e-04, 9.9619e-01, 2.8527e-03, 8.9843e-19, 3.2979e-19,
          1.7914e-18],
         [5.8241e-06, 9.4020e-01, 5.9792e-02, 9.2684e-12, 4.2602e-12,
          4.0171e-13],
         [4.3142e-09, 8.8218e-01, 1.1782e-01, 9.6889e-19, 2.6159e-19,
          2.1215e-18],
         [1.5678e-09, 1.8803e-01, 8.1197e-01, 2.2681e-17, 1.0570e-17,
          7.2514e-17],
         [5.3612e-05, 1.1938e-01, 8.8057e-01, 3.1977e-14, 3.3414e-14,
          1.2567e-14],
         [3.3132e-10, 8.8270e-01, 1.1730e-01, 3.7418e-20, 1.6218e-21,
          8.1419e-21]],

        [[5.4208e-02, 9.4337e-01, 2.4259e-03, 1.7896e-17, 1.2233e-17,
          3.4992e-18],
         [3.2598e-06, 9.8512e-01, 1.4873e-02, 3.5059e-15, 3.0056e-15,
          9.8784e-15],
         [2.4138e-07, 9.8244e-01, 1.7565e-02, 1.1519e-14, 8.4265e-14,
          7.3593e-15],
         [7.7745e-09, 5.3010e-01, 4.6990e-01, 7.3490e-16, 2.4701e-16,
          1.6945e-15],
         [4.0798e-12, 4.0282e-05, 9.9996e-01, 7.5887e-22, 1.7681e-21

In [11]:
real = torch.rand(3,5)
alpha = torch.rand(3,1)
alpha.expand(real.size())

tensor([[0.0425, 0.0425, 0.0425, 0.0425, 0.0425],
        [0.8052, 0.8052, 0.8052, 0.8052, 0.8052],
        [0.2623, 0.2623, 0.2623, 0.2623, 0.2623]])