In [6]:
from utils import *


In [2]:
x = [[13959,  1566,    12,  2968,    10,     1,    37,   511,  1921,    19,
            24,    13,     3,    35, 21933,    84,    56,     6,    13,   503,
             6,    43,     3,     9, 10710,  1113,     6,   321,    16,  1487,
          1208,    11, 20187,  1353,     5,     1,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [13959,  1566,    12,  2968,    10,     1,   101,   103,    59,   241,
            12,   143,     8,  1124,    13,  2259,  4131,    21,   128,  1440,
         31823,   120,    11,  1172,   135,    21,  1440,   224,    38,  9652,
            42,   119, 11811,  1440,     5,     1,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]]

In [3]:
d(x)

['translate English to German: The second challenge is that of enlargement which will, of course, have a considerable impact, both in budgetary and geographical terms.',
 'translate English to German: We do not want to make the conditions of competition worse for some countries unilaterally and improve them for countries such as Austria or other transit countries.']

In [5]:
d([[  316, 15402, 18386,  8962,    16,    74, 30346,     6,    67,  4512,
         27554,    15,     3, 27485,   219,   177,     3, 19594,    29,    64,
           873, 16407,  1779,  5728,   745,   551,     5,     1,     0,     0],
        [ 1185,  6056,   311,    67,     3, 19745,     7, 17391,   218,  4847,
         24886,   236, 13584, 10020,   109,   524,  2947,    64,   680,   218,
             3,     2, 12852,   401,  2903, 24885, 19881, 22372,     5,     1]])

['Die zweite Herausforderung besteht in der Erweiterung, die natürlich erhebliche Auswirkungen auf den wirtschaftlichen und geographischen Bereich haben wird.',
 'Wir wollen nicht die Wettbewerbsbedingungen für einige Länder einseitig verschlechtern und sie für sterreich oder andere Transitländer verbessern.']

In [6]:
d([[  316, 27932, 18386,  8962,    16,    74, 30346,     6,    67,  2662,
             3,    15,     3, 27485,   219,  1324, 21068, 17375,    29,    64,
           873, 16407,  1779,  5728,   745,   551,     5,     1,     1,   644],
        [ 1185,  6056,    67,   790,     3, 28510,     7, 17391,   219,  4847,
         24886,   236, 13584, 10020,    40,   524,  2947,    64,   680,   311,
          2903,     2, 12852,   401,  2903, 24885, 19881, 22372,     5,     1]])

['Die dritte Herausforderung besteht in der Erweiterung, die ja e Auswirkungen auf unsere Haushaltöffentlichenn und geographischen Bereich haben wird. Das',
 'Wir wollen die nur Regelnsbedingungen auf einige Länder einseitig verschlchtern und sie nicht anderesterreich oder andere Transitländer verbessern.']

In [1]:
import torch

In [5]:
model = torch.load('./model/G_AB.pt').eval()

In [9]:
pred,pred_attn  = en(['relating to establishing a framework framework for the development and development development of the European Union and the development development of the European Union and the development of the European Union and the development development of a framework framework framework for the development and development development of the European Union and the development development of a framework framework framework for the development and development development of the European Union and the development development of a framework framework framework for the development and development of the European Union and the development development of the European Union and the development of the European Union, and the development development of a reprehensible forestry.', 'relating to the issue of fraud and fraud fraud. – a report on the issue of fraud and fraud in the EU and the European Commission’s report on the issue of fraud prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention.'])

In [10]:
label,label_attn  = en(['I have some sympathy with the last speaker: sometimes the Committee on Budgetary Control gets so involved with the important work they are doing, that they are unable to see the wood for the trees.', 'I also welcome the presentation on behalf of the Legal Affairs Committee and the Economic and Monetary Affairs Committee which took a balanced approach to the major and indeed legitimate concerns of the Committee on Budgetary Control about fraud.'])

In [ ]:
model(pred,pred_attn)

In [1]:
import torch

In [29]:
inpu = torch.rand(1,requires_grad=False)
inpu
inpuB = torch.rand(1,requires_grad=False)
inpuB

tensor([0.8662])

In [30]:
W = torch.rand(1,requires_grad=True)
W
print(W)

tensor([0.9243], requires_grad=True)


In [31]:
output = W*inpu + inpuB

In [32]:
torch.autograd.grad(outputs=output, inputs=inpu,create_graph=True, retain_graph=True, only_inputs=True)

RuntimeError: One of the differentiated Tensors does not require grad

In [39]:

alpha = torch.rand((5, 1, 1),device=torch.device('cuda:0'))
onehot_real = torch.ones(5,4,3)
alpha = alpha.expand(onehot_real.size())

In [40]:
a = torch.ones(3,2,3)
b = torch.ones(3,4,3)

tensor([[[0.1400, 0.1400, 0.1400],
         [0.1400, 0.1400, 0.1400],
         [0.1400, 0.1400, 0.1400],
         [0.1400, 0.1400, 0.1400]],

        [[0.1348, 0.1348, 0.1348],
         [0.1348, 0.1348, 0.1348],
         [0.1348, 0.1348, 0.1348],
         [0.1348, 0.1348, 0.1348]],

        [[0.3880, 0.3880, 0.3880],
         [0.3880, 0.3880, 0.3880],
         [0.3880, 0.3880, 0.3880],
         [0.3880, 0.3880, 0.3880]],

        [[0.9078, 0.9078, 0.9078],
         [0.9078, 0.9078, 0.9078],
         [0.9078, 0.9078, 0.9078],
         [0.9078, 0.9078, 0.9078]],

        [[0.8082, 0.8082, 0.8082],
         [0.8082, 0.8082, 0.8082],
         [0.8082, 0.8082, 0.8082],
         [0.8082, 0.8082, 0.8082]]], device='cuda:0')