In [1]:
from utils import *


In [2]:
import torch

In [19]:
model = torch.load('./checkpoint/checkpoint/D_B.pt').eval().cuda()

In [12]:
l,l_attn  = en(['als die Unbekannten, und doch bekannt; als die Sterbenden, und siehe, wir leben; als die Gezüchtigten, und doch nicht ertötet;', 'als die Traurigen, aber allezeit fröhlich; als die Armen, aber die doch viele reich machen; als die nichts innehaben, und doch alles haben.', 'O ihr Korinther! unser Mund hat sich zu euch aufgetan, unser Herz ist weit.', "Ihr habt nicht engen Raum in uns; aber eng ist's in euren Herzen.", 'Ich rede mit euch als mit meinen Kindern, daß ihr euch auch also gegen mich stellet und werdet auch weit.', 'Ziehet nicht am fremden Joch mit den Ungläubigen. Denn was hat die Gerechtigkeit zu schaffen mit der Ungerechtigkeit? Was hat das Licht für Gemeinschaft mit der Finsternis?', 'Wie stimmt Christus mit Belial? Oder was für ein Teil hat der Gläubige mit dem Ungläubigen?', 'Was hat der Tempel Gottes für Gleichheit mit den Götzen? Ihr aber seid der Tempel des lebendigen Gottes; wie denn Gott spricht: "Ich will unter ihnen wohnen und unter ihnen wandeln und will ihr Gott sein, und sie sollen mein Volk sein.', 'Darum gehet aus von ihnen und sondert euch ab, spricht der HERR, und rührt kein Unreines an, so will ich euch annehmen', 'und euer Vater sein, und ihr sollt meine Söhne und Töchter sein, spricht der allmächtige HERR."'])

In [13]:
p,p_attn = en(['As unknown, und yet well known; as dying, and, behold, we live; as chastened, and not killed;', 'Als traurig, doch alway rejoicing; als arm, obwohl viele reich; als having nichts, und  yet possessing all things.', 'O ye Corinthians, unser Mund ist offen unto euch, unser Herz ist vergrößert.', 'Ye sind nicht straitened in uns, aber ye sind straitened in eurem eigenen Darm.', 'Nun für eine Rekompensation in dem gleichen, (Ich rede wie unto meinen Kindern,) sei ye auch enlarged.', 'Be ye nicht ungleich yoked zusammen mit ungläubigen: denn welche Gemeinschaft hath Rechtschaffenheit mit unrechteousness? und welche Kommunion hath Licht mit Finsternis?', 'Und was concord hat Christus mit Belial? oder welcher Teil hat er hat er, der glaubt mit einem Unidel?', 'Und welche Vereinbarung hat der Tempel Gottes mit idolen? denn ihr sind der Tempel des lebenden Gottes; wie Gott hat gesagt, ich will wohn in ihnen wohnen und trachten in ihnen; und ich werde ihnen meinen Gott sein, und sie werden mein Volk sein.', 'Wherefore come out from among them, and be ye separate, spricht the Lord, and touch not the unclean thing; and I will receive you,', 'Und wird ein Vater unto euch sein, und ihr werdet meine Sonen und Töchter sein, spricht der Herr mighty.'])

In [17]:
pred = l.cuda()
pred_attn = l.cuda()
label = p.cuda()
label_attn = p.cuda()

In [18]:
print(model(pred,pred_attn))
print(model(label,label_attn))

tensor([[-0.2182],
        [-0.2139],
        [-0.1539],
        [-0.3964],
        [-0.2606],
        [ 0.0069],
        [-0.0368],
        [-0.2651],
        [ 0.0657],
        [-0.0921]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[ 0.0795],
        [ 0.0727],
        [-0.4837],
        [-0.0967],
        [-0.2072],
        [-0.3011],
        [-0.1369],
        [-0.2582],
        [ 0.0871],
        [-0.0553]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [10]:
label,label_attn  = en(['I have some sympathy with the last speaker: sometimes the Committee on Budgetary Control gets so involved with the important work they are doing, that they are unable to see the wood for the trees.', 'I also welcome the presentation on behalf of the Legal Affairs Committee and the Economic and Monetary Affairs Committee which took a balanced approach to the major and indeed legitimate concerns of the Committee on Budgetary Control about fraud.'])

In [ ]:
model(pred,pred_attn)

In [1]:
import torch

In [29]:
inpu = torch.rand(1,requires_grad=False)
inpu
inpuB = torch.rand(1,requires_grad=False)
inpuB

tensor([0.8662])

In [30]:
W = torch.rand(1,requires_grad=True)
W
print(W)

tensor([0.9243], requires_grad=True)


In [31]:
output = W*inpu + inpuB

In [32]:
torch.autograd.grad(outputs=output, inputs=inpu,create_graph=True, retain_graph=True, only_inputs=True)

RuntimeError: One of the differentiated Tensors does not require grad

In [39]:

alpha = torch.rand((5, 1, 1),device=torch.device('cuda:0'))
onehot_real = torch.ones(5,4,3)
alpha = alpha.expand(onehot_real.size())

In [41]:
a = torch.ones(3,2,3)
b = torch.ones(3,4,3)

In [42]:
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [43]:
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [47]:
torch.sum(a,b)

TypeError: sum() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [40]:
d([[ 7272,   266,     7,   229,  8330,    10,  8262,  1301,   558,    16,
           74,     3, 30604,    29,  3545,   170,   645, 23072,    35,  7510,
          425,  4714,     6,     3, 20740,    74,   781, 12319,   311,    46,
         1324,    29, 23877,     6,     3,    49,   510,   860,    60,   155,
           15,    17,   680,     5,     1]])

['Denn eines ist klar: Selbst wenn wir in der Europäischen Union zu einer ausgezeichneten Regelung kommen, hört der Verkehr nicht an unseren Grenzen, er überschreitet sie.']

In [41]:
d([[ 1674,  6509,  8301,   340, 19146,    49, 15679,    49,     6,  8816,
           29, 16608,     6,   218,  1834,  5512,   170,     3,  1878,  6973,
            3, 23020,     5,     1,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]])

['Ich möchte daher dem Berichterstatter, Herrn Koch, für seine Arbeit zu dieser Frage danken.']

In [1]:
import torch

In [59]:
gradient_penalty = torch.load('./checkpoint/gradient_penalty.pt')
gradient = torch.load('./checkpoint/gradient.pt')
interpolates = torch.load('./checkpoint/interpolates.pt')
onehot_real = torch.load('./checkpoint/onehot_real.pt')
fake = torch.load('./checkpoint/fake.pt')
output = torch.load('./checkpoint/output.pt')
real = torch.load('./checkpoint/real.pt')
fake_ = torch.load('./checkpoint/fake_.pt')
alpha = torch.load('./checkpoint/alpha.pt')

In [87]:
torch.clip(alpha, min=1e-2)

tensor([[[0.6736]],

        [[0.1732]],

        [[0.0100]],

        [[0.3951]]], device='cuda:0')

In [61]:
d([real[-2]])

['I would like, first of all, to thank the rapporteur for his exceptionally accurate and technical work on the report and, secondly, the Commission for the proposal it has submitted.']

In [62]:
d([torch.argmax(fake_[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [63]:
d([torch.argmax(fake[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [64]:
d([torch.argmax(onehot_real[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [79]:
torch.max(interpolates[-2],-1)

torch.return_types.max(
values=tensor([9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9

In [80]:
1-(interpolates[:, :,0]>1e-3).long()

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,

In [75]:
output

tensor([[0.1348],
        [0.0587],
        [0.0330],
        [0.0602]], device='cuda:0', requires_grad=True)

In [74]:
torch.max(gradient[-2],-1)

torch.return_types.max(
values=tensor([1.1048e-02, 7.9653e-03, 6.0113e-03, 5.5646e-03, 1.9542e-02, 1.3272e-02,
        7.2185e-03, 1.3174e-02, 8.0519e-03, 1.2683e-02, 4.3365e-03, 3.6778e-03,
        3.5361e-03, 3.4416e-03, 5.2472e-03, 1.0689e-02, 4.5117e-03, 5.3209e-03,
        5.8149e-03, 4.3310e-03, 1.0768e-02, 6.1060e-03, 2.5659e-03, 5.4847e-03,
        1.3335e-02, 1.1511e-02, 4.0305e-03, 3.6598e-03, 5.6789e-03, 9.4820e-03,
        1.5657e-02, 8.7381e-03, 7.0189e-03, 3.3296e-02, 7.5614e-02, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1302e+01, 2.4101e+01,
        2.0388e+01, 1.9873e+01, 2.0791e+01, 2.4457e+01, 2.1025e+01, 4.8850e+01,
        9.2354e+01, 2.7918e+01, 1.2031e+01, 1.7346e+01, 1.7141e+01, 1.1054e+01,
        1.7246e+01, 1.7372e+01, 1.8897e+01, 1.8529e+01, 1.7869e+01, 2.4627e+01,
        1.3377e+01, 1.4612e+01, 1.4314e+01, 1.5957e+01, 1.5814e+01, 1.5940e+01,
        1

In [68]:
((gradient.norm(2, dim=1) - 1) ** 2).mean(-1)[-2]

tensor(40464.6172, device='cuda:0', grad_fn=<SelectBackward0>)

In [4]:
en(['周'])

(tensor([[3, 2, 1]]), tensor([[1, 1, 1]]))

In [5]:
en(['hi'])

(tensor([[7102,    1]]), tensor([[1, 1]]))

In [7]:
en(['nidwnaidnaiwdhaiwhda'])

(tensor([[   3,   29,   23,   26,  210,   29, 6146,   29,    9,   23,  210,   26,
          1024,   23,  210,  107,   26,    9,    1]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))

In [8]:

from datasets import load_dataset,load_metric
load_dataset("bible_para", lang1="de", lang2="en").shape

Using custom data configuration de-en-lang1=de,lang2=en
Reusing dataset bible_para (C:\Users\kevin\.cache\huggingface\datasets\bible_para\de-en-lang1=de,lang2=en\0.0.0\b6cc20bcbfb0299beeba1dcc80a8420b975938ca0eef75b3ed30b50df7d950b1)
100%|██████████| 1/1 [00:00<00:00, 100.27it/s]


{'train': (62195, 2)}