In [2]:
from utils import *


In [3]:
d([[13774,    10,     1,   292,     3,  3473,  1255,  1159, 24776,    29,
            64,  1650,  7900,    46,  1609,  7921,    29,  2217,   218,    67,
           472,  5666,     6,   218,    67,   391,  1864,   440,    15,    64,
           218,    67,   325,   635,     6,   559,  1159,    52, 10436,     6,
           559,    74,   781, 10660,   117,     1]])

['classification: Sie servieren ihre Speisen und ihr Angebot an Getränken für die Stiere, für die Räume und für die Lamm, nach ihrer Zahl, nach der Verordnung;']

In [3]:
import torch

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

In [9]:


bart  =  AutoModelForSeq2SeqLM.from_pretrained('facebook/bart-base').cuda().eval()
t5  =  AutoModelForSeq2SeqLM.from_pretrained('t5-small').cuda().eval()

In [10]:
t5

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro

In [7]:
bart

BartForConditionalGeneration(
  (model): BartModel(
    (shared): Embedding(50265, 768, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): Embedding(50265, 768, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 768)
      (layers): ModuleList(
        (0): BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (final_layer_norm): LayerNorm((768,), eps=1e-05,

In [14]:
a,a_attn = en(['translate English to German: This is my best friend, his name is kevin'])

In [15]:
d(G_AB.generate(a.cuda()))

['Dies ist mein bester Freund, sein Name ist kevin']

In [4]:
D_A

D(
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (layer

In [4]:
a,a_attn = en([ 'As unknown, and yet well known; as dying, and, behold, we live; as chastened, and not killed;'])
b,b_attn = en([ 'als die Unbekannten, und doch bekannt; als die Sterbenden, und siehe, wir leben; als die Gezüchtigten, und doch nicht ertötet;'])
out = G_BA(b.cuda(),b_attn.cuda(),a.cuda(),a_attn.cuda())


In [5]:
out_pre = GABpretrained(b.cuda(),b_attn.cuda(),a.cuda(),a_attn.cuda())

In [6]:
torch.max(out_pre.logits,-1)

torch.return_types.max(
values=tensor([[ -4.4404,  -2.9787,  -5.6132,  -5.8000,  -5.0923,  -3.6677,  -3.4350,
          -7.2339,  -6.2516,  -5.5453,  -2.3706,  -6.3663,  -6.8154,  -6.2813,
          -4.0113,  -4.2502,  -3.7758,  -4.6080,  -8.1003,  -7.6774,  -5.1197,
          -5.5543, -10.2046,  -6.5408,  -2.3887,  -2.7787,  -3.4548,  -2.1444,
          -2.1556,  -6.5836,  -4.5876]], device='cuda:0',
       grad_fn=<MaxBackward0>),
indices=tensor([[    6,     6,    62,   780,   801,   117,   117,    38, 13677,     6,
            11,   217,    62,     6,     6,    62,   619,   117,    38,   273,
             7,     7,    15,     7,     6,    11,    59,  4792,   117,   117,
             1]], device='cuda:0'))

In [8]:
out.logits[0][-3]

tensor([-24.2463, -10.4377, -13.2240,  ..., -40.4194, -40.4150, -40.4626],
       device='cuda:0', grad_fn=<SelectBackward0>)

In [7]:
d(torch.argmax(out.logits,-1))

[' evil, and knowing known known; heaven dead dead heaven heaven heaven heaven; heaven live; heaven dyingsanctst;; and sacrifice sacrifice;;']

In [19]:
a,a_attn = en(['Unbekannten, und doch bekannt'])
D_B(a.cuda(),a_attn.cuda())

tensor([[-4.8364]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [23]:
if(torch.rand(1)):
    print(1)

1


In [32]:
gradient_penalty = torch.load('./checkpoint/checkpoint4/gradient_penalty.pt')
gradient = torch.load('./checkpoint/checkpoint4/gradient.pt')
real = torch.load('./checkpoint/checkpoint4/real.pt')
interpolates = torch.load('./checkpoint/checkpoint4/interpolates.pt')

In [33]:
gradient_penalty

tensor(10.7367, device='cuda:0', requires_grad=True)

In [48]:
d([torch.argmax(interpolates[10],-1)])

['Wenn in diesen Prozess das gemeinsame reiche Kulturerbe dieser Länder integriert wird, bin ich zuversichtlich, dass mittel- und langfristig wichtige Ergebnisse und Erfolge erzielt werden können.']

In [45]:
d([torch.argmax(gradient[10],-1)])

['orialister classificationAsadar spum incadr spum incadr classificationAsadar incadr taiat incadr incadr classification spum dimineata jumataterosvig jumatate classification gradiniillon incadrAsadarvigfaser classification gradini golf lucrari incadr gradini gradini lucrari incadr incadr taiatros Județean masini Est']

In [26]:
torch.max(gradient,-1)

torch.return_types.max(
values=tensor([[5.4904e-02, 2.1900e-02, 2.5657e-02, 1.9702e-02, 7.2296e-03, 2.2675e-02,
         1.4587e-02, 2.4221e-02, 1.7074e-02, 9.5207e-03, 1.1801e-02, 6.9745e-03,
         6.4295e-03, 1.0668e-02, 2.0614e-02, 1.8782e-02, 7.4033e-02, 1.4009e-01,
         2.4670e-02, 1.1591e-02, 2.0104e-02, 2.4679e-02, 9.6228e-03, 2.7291e-02,
         1.4249e-02, 1.9200e-02, 8.4734e-03, 7.8033e-03, 6.2466e-03, 1.1784e-02,
         7.7865e-03, 7.3719e-02, 1.0434e-01],
        [2.7529e+00, 1.4099e+00, 2.5301e+00, 4.2901e+00, 1.8324e+00, 4.8085e-01,
         1.1282e+00, 3.5699e-01, 2.3046e+00, 9.3882e-01, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.2221e-01, 3.0482e-02, 1.3381e-02, 2.4217e-02, 1.0227e-02

In [5]:

G = torch.load('./checkpoint/G_AB.pt').cuda().eval()

In [20]:



real,real_attn = en(['As unknown, and yet well known; as dying, and, behold, we live; as chastened, and not killed'])
target,target_attn = en( ['As unknown, and yet well known; as dying, and, behold, we live; as chastened, and not killedn; als verzweizweimder und nicht nicht get getötdetet.'])


real,real_attn = G.add_prefix(real.cuda(),real_attn.cuda())
print('input',d(real))
print('output',d(target))



print('generate',d(GABpretrained.generate(real)))
forwardout = GABpretrained.forward(input_ids=real.cuda(),attention_mask=real_attn.cuda(),labels=target.cuda(),decoder_attention_mask =target_attn.cuda())
print(forwardout.loss)
print('predictoutput',d(torch.argmax(forwardout.logits,-1)))

cri = torch.nn.CrossEntropyLoss(ignore_index=0)
print(forwardout.logits.reshape(-1,forwardout.logits.shape[-1]).shape)
print(target.reshape(-1).shape)
cri(forwardout.logits.reshape(-1,forwardout.logits.shape[-1]),target.reshape(-1).cuda())

input ['translate English to German: As unknown, and yet well known; as dying, and, behold, we live; as chastened, and not killed']
output ['As unknown, and yet well known; as dying, and, behold, we live; as chastened, and not killedn; als verzweizweimder und nicht nicht get getötdetet.']
generate ['Und siehe, wir leben; als enttäuscht und nicht getöt']
tensor(2.5436, device='cuda:0', grad_fn=<NllLossBackward0>)
predictoutput ['Und, and yet well known; as dying, and, hold, we live; as chastened, and not killed. wfelfelt, nicht get getöötet...']
torch.Size([50, 32128])
torch.Size([50])


tensor(2.5436, device='cuda:0', grad_fn=<NllLossBackward0>)

In [ ]:
loss = GABpretrained.forward(input_ids=real.cuda(),attention_mask=real_attn.cuda(),labels=target.cuda(),decoder_attention_mask =target_attn.cuda()).loss


In [107]:
print(d([[  501,    67,   597, 21943,     6,]]))
d([[ 2203,     3,    73, 27570,    64,]])

['als die Unbekannten,']


['Und  unbekannt und']

In [95]:
target

tensor([[  501,    67,   597, 21943,     6,    64,  4178,  7324,   117,   501,
            67,  3557, 10222,   537,     6,    64,     3, 25241,     6,   558,
         13180,   117,   501,    67,   350,   457, 31116,   324,     6,    64,
          4178,   311,     3,    49,    17,  1872,    17,    15,    17,   117,
             1]])

In [70]:
d(GABpretrained.generate(real.cuda()))

['As unknown, and yet well known; as unknown, and yet well known; as dying,']

In [76]:

G.forward(real.cuda(),(real>0.5).long().cuda(),real.cuda(),(real>0.5).long().cuda()).loss

tensor(2.1596, device='cuda:0', grad_fn=<NllLossBackward0>)

In [6]:
gradient_penalty

tensor(10.4385, device='cuda:0', requires_grad=True)

In [9]:
(gradient.mean(-1).norm(2,1) - 1) ** 2

tensor([3.1097e-02, 4.4483e-04, 1.6283e-01, 4.1560e+01], device='cuda:0',
       grad_fn=<PowBackward0>)

In [11]:
torch.max(interpolates,-1)

torch.return_types.max(
values=tensor([[0.5056, 0.5056, 0.5056, 0.5056, 0.5056, 0.5056, 0.5056, 0.5056, 0.5056,
         0.5056, 0.5056, 0.5056, 0.5056, 0.5056, 0.5056, 0.5056, 0.5056, 0.5056,
         0.5056, 0.5056, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944,
         0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944,
         0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944,
         0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944,
         0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944,
         0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944, 0.4944,
         0.4944, 0.4944, 0.4944],
        [0.8397, 0.8397, 0.8397, 0.8397, 0.8397, 0.8397, 0.8397, 0.8397, 0.8397,
         0.8397, 0.8397, 0.8397, 0.8397, 0.8397, 0.8397, 0.8397, 0.8397, 0.8397,
         0.8397, 0.8397, 0.1603, 0.1603, 0.1603, 0.1603, 0.1603, 0.1603, 0.1603,
         0.1603, 0.1603, 0.1603, 0.1603, 0.1

In [29]:
gradient[-1].mean(-1)[36]

tensor(7.3186, device='cuda:0', grad_fn=<SelectBackward0>)

In [30]:
gradient[-1][36]

tensor([10.4062, 11.5880,  7.9444,  ...,  0.0000,  0.0000,  0.0000],
       device='cuda:0', grad_fn=<SelectBackward0>)

In [33]:
real[-1]

tensor([   37,    29, 18240,  4728,    30,   112,   522,     6,    11, 24524,
            6,    11,   243,    16,   112,   842,     6,    96,   518,  1092,
            3,     9,   861,    36,  2170,    12,   376,   113,    19,    80,
         6189,   203,   625,    58,  2003,  8077,     6,   113,    19,  4169,
           17,    63,   203,   625,     6,   428,  3879,  4609,     1,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0], device='cuda:0')

In [31]:
fake_[-1][36]

IndexError: index 36 is out of bounds for dimension 0 with size 32

In [15]:
alpha[-1]

tensor([[0.0101]], device='cuda:0')

In [16]:
torch.max(interpolates[-1],-1)

torch.return_types.max(
values=tensor([0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899,
        0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899,
        0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.9899,
        0.9899, 0.9899, 0.9899, 0.9899, 0.9899, 0.0101, 0.0101, 0.0101, 0.0101,
        0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101,
        0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101,
        0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101,
        0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101, 0.0101,
        0.0101, 0.0101, 0.0101], device='cuda:0', grad_fn=<MaxBackward0>),
indices=tensor([ 9528,    18,  1201,    18,  1490, 20990,    18, 21417,   877,   147,
            8,  8022,  2303,     5,     1,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            

In [ ]:
torch.linalg.norm(gradient,dim=1)

In [54]:
gradient.reshape(-1,gradient.shape[-1]).shape

torch.Size([4640, 32128])

In [48]:
a = torch.tensor([[1,2],[2,3]]).float()

In [49]:
a

tensor([[1., 2.],
        [2., 3.]])

In [47]:
torch.linalg.norm(a,2)

tensor(4.2361)

In [32]:
gradient.mean(-1).mean(-1)

tensor([-2.8194e-05, -2.5746e-01,  3.3615e-04,  8.5097e-05, -2.4574e-03,
        -8.0596e-05, -2.8488e-03,  3.9071e-04, -2.9613e-03,  8.8507e-03,
         1.1199e-03, -1.4956e-04,  3.8724e-03, -7.4023e-05, -2.6217e-04,
        -1.8490e-03, -3.7379e-05, -1.4288e-03, -1.0575e-04, -6.4346e-03,
         3.2036e-03, -8.3305e-04,  4.0915e-03,  1.3936e-03, -2.3830e-04,
        -5.0008e-04,  1.9536e-03, -1.0561e-02,  4.0024e-04,  1.6444e-04,
         1.6214e-03, -3.5705e-04], device='cuda:0', grad_fn=<MeanBackward1>)

In [33]:
alpha.squeeze()

tensor([0.7285, 0.0192, 0.1501, 0.5312, 0.8115, 0.6848, 0.0281, 0.3060, 0.2812,
        0.5949, 0.1318, 0.5216, 0.0611, 0.0717, 0.1639, 0.7610, 0.5015, 0.7643,
        0.3389, 0.1570, 0.0825, 0.8208, 0.0847, 0.1470, 0.0324, 0.4760, 0.6103,
        0.9904, 0.7414, 0.2491, 0.6906, 0.5519], device='cuda:0')

In [84]:
p,p_attn  = en(['As unknown, and yet well known; as dying, and, behold, we live; as chastened, and not killed;', 'As sorrowful, yet alway rejoicing; as poor, yet making many rich; as having nothing, and yet possessing all things.', 'O ye Corinthians, our mouth is open unto you, our heart is enlarged.', 'Ye are not straitened in us, but ye are straitened in your own bowels.', 'Now for a recompence in the same, (I speak as unto my children,) be ye also enlarged.', 'Be ye not unequally yoked together with unbelievers: for what fellowship hath righteousness with unrighteousness? and what communion hath light with darkness?', 'And what concord hath Christ with Belial? or what part hath he that believeth with an infidel?', 'And what agreement hath the temple of God with idols? for ye are the temple of the living God; as God hath said, I will dwell in them, and walk in them; and I will be their God, and they shall be my people.', 'Wherefore come out from among them, and be ye separate, saith the Lord, and touch not the unclean thing; and I will receive you,', 'And will be a Father unto you, and ye shall be my sons and daughters, saith the Lord Almighty.'])

In [85]:
l,l_attn  = en(['as the unknown, and yet known; as the dead, and siehe, we live; as the gods, and not ert;', 'as the Traurigens, but all time fröhlich; as the poor, but who make many rich; as the who do nothing, and yet all have.', 'O their corinther! our mouth has risen to you, our heart is far.', "Your habt not engen space in us; but eng is's in euren heart.", 'I talk with you as with my children, that your also against me, and will also go far.', 'Ziehet not am fremden Joch with the ungläubigen. For what has the justice to create with the injustice? What has the light for the Community with the Finsternis?', 'How does Christ obey with Belial? Or what for a part has the God with the Ungläubigen?', 'What has the temple of God for equality with the gods? Your but the temple of the living God; as God says: "I will living under them and under them... and will their God, and they will my people.', 'Therefore het from them and sonder you ab, he speaks theHER, and does not touch an unreine, so I will take you.', 'and your father be, and her shall be my son and techter, spricht the all-mighty HERR."'])

In [86]:
pred = p.cuda()
pred_attn = p_attn.cuda()
label =l.cuda()
label_attn = l_attn.cuda()

In [90]:
a = (model(label,label_attn)-model(pred,pred_attn))
a.sum()


tensor(0.5967, device='cuda:0', grad_fn=<SumBackward0>)

In [10]:
label,label_attn  = en(['I have some sympathy with the last speaker: sometimes the Committee on Budgetary Control gets so involved with the important work they are doing, that they are unable to see the wood for the trees.', 'I also welcome the presentation on behalf of the Legal Affairs Committee and the Economic and Monetary Affairs Committee which took a balanced approach to the major and indeed legitimate concerns of the Committee on Budgetary Control about fraud.'])

In [ ]:
model(pred,pred_attn)

In [1]:
import torch

In [29]:
inpu = torch.rand(1,requires_grad=False)
inpu
inpuB = torch.rand(1,requires_grad=False)
inpuB

tensor([0.8662])

In [30]:
W = torch.rand(1,requires_grad=True)
W
print(W)

tensor([0.9243], requires_grad=True)


In [31]:
output = W*inpu + inpuB

In [32]:
torch.autograd.grad(outputs=output, inputs=inpu,create_graph=True, retain_graph=True, only_inputs=True)

RuntimeError: One of the differentiated Tensors does not require grad

In [39]:

alpha = torch.rand((5, 1, 1),device=torch.device('cuda:0'))
onehot_real = torch.ones(5,4,3)
alpha = alpha.expand(onehot_real.size())

In [41]:
a = torch.ones(3,2,3)
b = torch.ones(3,4,3)

In [42]:
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [43]:
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [47]:
torch.sum(a,b)

TypeError: sum() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [40]:
d([[ 7272,   266,     7,   229,  8330,    10,  8262,  1301,   558,    16,
           74,     3, 30604,    29,  3545,   170,   645, 23072,    35,  7510,
          425,  4714,     6,     3, 20740,    74,   781, 12319,   311,    46,
         1324,    29, 23877,     6,     3,    49,   510,   860,    60,   155,
           15,    17,   680,     5,     1]])

['Denn eines ist klar: Selbst wenn wir in der Europäischen Union zu einer ausgezeichneten Regelung kommen, hört der Verkehr nicht an unseren Grenzen, er überschreitet sie.']

In [41]:
d([[ 1674,  6509,  8301,   340, 19146,    49, 15679,    49,     6,  8816,
           29, 16608,     6,   218,  1834,  5512,   170,     3,  1878,  6973,
            3, 23020,     5,     1,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]])

['Ich möchte daher dem Berichterstatter, Herrn Koch, für seine Arbeit zu dieser Frage danken.']

In [1]:
import torch

In [59]:
gradient_penalty = torch.load('./checkpoint/gradient_penalty.pt')
gradient = torch.load('./checkpoint/gradient.pt')
interpolates = torch.load('./checkpoint/interpolates.pt')
onehot_real = torch.load('./checkpoint/onehot_real.pt')
fake = torch.load('./checkpoint/fake.pt')
output = torch.load('./checkpoint/output.pt')
real = torch.load('./checkpoint/real.pt')
fake_ = torch.load('./checkpoint/fake_.pt')
alpha = torch.load('./checkpoint/alpha.pt')

In [87]:
torch.clip(alpha, min=1e-2)

tensor([[[0.6736]],

        [[0.1732]],

        [[0.0100]],

        [[0.3951]]], device='cuda:0')

In [61]:
d([real[-2]])

['I would like, first of all, to thank the rapporteur for his exceptionally accurate and technical work on the report and, secondly, the Commission for the proposal it has submitted.']

In [62]:
d([torch.argmax(fake_[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [63]:
d([torch.argmax(fake[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [64]:
d([torch.argmax(onehot_real[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [79]:
torch.max(interpolates[-2],-1)

torch.return_types.max(
values=tensor([9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9

In [80]:
1-(interpolates[:, :,0]>1e-3).long()

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,

In [75]:
output

tensor([[0.1348],
        [0.0587],
        [0.0330],
        [0.0602]], device='cuda:0', requires_grad=True)

In [74]:
torch.max(gradient[-2],-1)

torch.return_types.max(
values=tensor([1.1048e-02, 7.9653e-03, 6.0113e-03, 5.5646e-03, 1.9542e-02, 1.3272e-02,
        7.2185e-03, 1.3174e-02, 8.0519e-03, 1.2683e-02, 4.3365e-03, 3.6778e-03,
        3.5361e-03, 3.4416e-03, 5.2472e-03, 1.0689e-02, 4.5117e-03, 5.3209e-03,
        5.8149e-03, 4.3310e-03, 1.0768e-02, 6.1060e-03, 2.5659e-03, 5.4847e-03,
        1.3335e-02, 1.1511e-02, 4.0305e-03, 3.6598e-03, 5.6789e-03, 9.4820e-03,
        1.5657e-02, 8.7381e-03, 7.0189e-03, 3.3296e-02, 7.5614e-02, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1302e+01, 2.4101e+01,
        2.0388e+01, 1.9873e+01, 2.0791e+01, 2.4457e+01, 2.1025e+01, 4.8850e+01,
        9.2354e+01, 2.7918e+01, 1.2031e+01, 1.7346e+01, 1.7141e+01, 1.1054e+01,
        1.7246e+01, 1.7372e+01, 1.8897e+01, 1.8529e+01, 1.7869e+01, 2.4627e+01,
        1.3377e+01, 1.4612e+01, 1.4314e+01, 1.5957e+01, 1.5814e+01, 1.5940e+01,
        1

In [68]:
((gradient.norm(2, dim=1) - 1) ** 2).mean(-1)[-2]

tensor(40464.6172, device='cuda:0', grad_fn=<SelectBackward0>)

In [4]:
en(['周'])

(tensor([[3, 2, 1]]), tensor([[1, 1, 1]]))

In [5]:
en(['hi'])

(tensor([[7102,    1]]), tensor([[1, 1]]))

In [7]:
en(['nidwnaidnaiwdhaiwhda'])

(tensor([[   3,   29,   23,   26,  210,   29, 6146,   29,    9,   23,  210,   26,
          1024,   23,  210,  107,   26,    9,    1]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))