In [22]:
from utils import *


In [23]:
import torch

In [93]:
gradient_penalty = torch.load('./checkpoint/checkpoint/gradient_penalty.pt')
alpha = torch.load('./checkpoint/checkpoint/alpha.pt')
fake_ = torch.load('./checkpoint/checkpoint/fake_.pt')
gradient = torch.load('./checkpoint/checkpoint/gradient.pt')
real = torch.load('./checkpoint/checkpoint/real.pt')
interpolates = torch.load('./checkpoint/checkpoint/interpolates.pt')

In [95]:
gradient= gradient[1]

In [111]:
torch.set_printoptions(threshold=100000000)

In [121]:
torch.max(interpolates[1],-1)

torch.return_types.max(
values=tensor([0.9808, 1.0000, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808,
        0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808,
        0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808,
        0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808,
        0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808,
        0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808,
        0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808,
        0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.9808, 0.0192,
        0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192,
        0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192,
        0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192,
        0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192, 0.0192,
        0

In [114]:
real[1]

tensor([  878,    36,    89,     9,   107,    40,    74, 17191,  4603,   221,
         2168,     9,     6,     3,    26,  7118,   388,   446,    49, 11658,
          256,  1526,   107,   858,    93,   961,    89,  7423,    29,  3818,
            7,     3, 22707,  3402,     6,    64,     3, 10325,  6889,    93,
        12477,   236,   325,  2317,    77,  4027,    17,  6314,   403,    74,
          272, 20201,    49,   122,  3974,     6,  1005,     3,    26,  7118,
         3532,  4027,    17,    16,    74,  3287, 13010,   172,  7392,    17,
          615,     5,  1203, 26555,   446,    49, 11658,   256,  1526,   107,
          858,    93,   961,    89,  7423,    29,  3818,     7,     5,     1,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0, 

In [119]:
alpha[1]

tensor([[0.0192]], device='cuda:0')

In [118]:
torch.max(fake_[1],-1)

torch.return_types.max(
values=tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
       device='cuda:0', grad_fn=<MaxBackward0>),
indices=tensor([11565,    36,  5497, 15717,  5622,     9,  1110,  5717,     7, 14060,
            6,  7153,  2370,    67, 15402,     6,    64,    71, 14888,   107,
           67, 27932,     6,     1,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,   

In [112]:
interpolates[1][81]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0192, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 

In [104]:
gradient[81]

tensor([41.3708, 41.0375,  2.1837,  ...,  0.0000,  0.0000,  0.0000],
       device='cuda:0', grad_fn=<SelectBackward0>)

In [101]:
torch.max(gradient.mean(-1),-1)

torch.return_types.max(
values=tensor(20.7977, device='cuda:0', grad_fn=<MaxBackward0>),
indices=tensor(81, device='cuda:0'))

In [94]:
((gradient.mean(-1).norm(2,1) - 1) ** 2)

tensor([9.8629e-01, 7.7097e+02, 7.4003e-01, 9.5578e-01, 4.3858e-01, 9.6860e-01,
        4.8878e-01, 9.4909e-01, 6.4582e-01, 3.5173e-01, 4.8819e-01, 9.5032e-01,
        6.4425e-01, 8.0440e-01, 6.6655e-01, 7.0494e-02, 9.8871e-01, 6.6818e-01,
        9.6991e-01, 3.8257e-01, 7.7215e-01, 8.0633e-01, 4.7734e-01, 6.8746e-01,
        5.2621e-01, 5.7030e-01, 5.5205e-01, 2.4224e-01, 9.0928e-01, 8.9703e-01,
        2.4220e-02, 9.4095e-01], device='cuda:0', grad_fn=<PowBackward0>)

In [65]:
torch.max(interpolates[-2],-1)

torch.return_types.max(
values=tensor([0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906, 0.6906,
        0

In [27]:
gradient_penalty

tensor(36.1473, device='cuda:0', requires_grad=True)

In [73]:
gradient.norm(2, dim=-1).mean()

tensor(5.9440, device='cuda:0', grad_fn=<MeanBackward0>)

In [83]:
gradient = gradient[:2]

In [86]:
gradient[0][0]

tensor([ 0.0004,  0.0003, -0.0024,  ...,  0.0000,  0.0000,  0.0000],
       device='cuda:0', grad_fn=<SelectBackward0>)

In [85]:
gradient.mean(-1).norm(2,1)

tensor([6.8788e-03, 2.8766e+01], device='cuda:0', grad_fn=<NormBackward1>)

In [84]:
torch.linalg.norm(gradient.reshape(gradient.shape[0],-1))

tensor(6220.2822, device='cuda:0', grad_fn=<CopyBackwards>)

In [80]:
((gradient.norm(2, dim=-1).norm(2, dim=-1) - 1) ** 2)

tensor([5.3132e-01, 3.8679e+07, 1.3766e+03, 2.5371e+01, 9.7517e+03, 5.5288e+00,
        6.5306e+03, 3.6542e+01, 2.0462e+03, 7.8796e+03, 8.6489e+03, 1.6947e+01,
        2.3404e+03, 7.9430e+02, 2.4641e+03, 3.2748e+04, 9.8176e-01, 1.8028e+03,
        5.0549e+00, 8.6662e+03, 1.1591e+03, 7.4882e+02, 7.5703e+03, 1.5145e+03,
        4.2187e+03, 3.7074e+03, 7.3193e+03, 1.5957e+04, 1.0691e+02, 1.4662e+02,
        5.7031e+04, 3.5553e+01], device='cuda:0', grad_fn=<PowBackward0>)

In [37]:
gradient.shape

torch.Size([32, 145, 32128])

In [78]:
gradient.norm(2, dim=-1).norm(2, dim=-1)

tensor([1.7289e+00, 6.2203e+03, 3.8103e+01, 6.0369e+00, 9.9751e+01, 3.3513e+00,
        8.1812e+01, 7.0450e+00, 4.6235e+01, 8.9767e+01, 9.3999e+01, 5.1167e+00,
        4.9378e+01, 2.9183e+01, 5.0640e+01, 1.8197e+02, 1.9908e+00, 4.3459e+01,
        3.2483e+00, 9.4092e+01, 3.5045e+01, 2.8365e+01, 8.8007e+01, 3.9917e+01,
        6.5951e+01, 6.1889e+01, 8.6553e+01, 1.2732e+02, 1.1340e+01, 1.3108e+01,
        2.3981e+02, 6.9626e+00], device='cuda:0', grad_fn=<NormBackward1>)

In [52]:
((gradient.norm(2, dim=1) - 1) ** 2)

tensor(30141468., device='cuda:0', grad_fn=<PowBackward0>)

In [ ]:
torch.linalg.norm(gradient,dim=1)

In [54]:
gradient.reshape(-1,gradient.shape[-1]).shape

torch.Size([4640, 32128])

In [48]:
a = torch.tensor([[1,2],[2,3]]).float()

In [49]:
a

tensor([[1., 2.],
        [2., 3.]])

In [47]:
torch.linalg.norm(a,2)

tensor(4.2361)

In [32]:
gradient.mean(-1).mean(-1)

tensor([-2.8194e-05, -2.5746e-01,  3.3615e-04,  8.5097e-05, -2.4574e-03,
        -8.0596e-05, -2.8488e-03,  3.9071e-04, -2.9613e-03,  8.8507e-03,
         1.1199e-03, -1.4956e-04,  3.8724e-03, -7.4023e-05, -2.6217e-04,
        -1.8490e-03, -3.7379e-05, -1.4288e-03, -1.0575e-04, -6.4346e-03,
         3.2036e-03, -8.3305e-04,  4.0915e-03,  1.3936e-03, -2.3830e-04,
        -5.0008e-04,  1.9536e-03, -1.0561e-02,  4.0024e-04,  1.6444e-04,
         1.6214e-03, -3.5705e-04], device='cuda:0', grad_fn=<MeanBackward1>)

In [33]:
alpha.squeeze()

tensor([0.7285, 0.0192, 0.1501, 0.5312, 0.8115, 0.6848, 0.0281, 0.3060, 0.2812,
        0.5949, 0.1318, 0.5216, 0.0611, 0.0717, 0.1639, 0.7610, 0.5015, 0.7643,
        0.3389, 0.1570, 0.0825, 0.8208, 0.0847, 0.1470, 0.0324, 0.4760, 0.6103,
        0.9904, 0.7414, 0.2491, 0.6906, 0.5519], device='cuda:0')

In [84]:
p,p_attn  = en(['As unknown, and yet well known; as dying, and, behold, we live; as chastened, and not killed;', 'As sorrowful, yet alway rejoicing; as poor, yet making many rich; as having nothing, and yet possessing all things.', 'O ye Corinthians, our mouth is open unto you, our heart is enlarged.', 'Ye are not straitened in us, but ye are straitened in your own bowels.', 'Now for a recompence in the same, (I speak as unto my children,) be ye also enlarged.', 'Be ye not unequally yoked together with unbelievers: for what fellowship hath righteousness with unrighteousness? and what communion hath light with darkness?', 'And what concord hath Christ with Belial? or what part hath he that believeth with an infidel?', 'And what agreement hath the temple of God with idols? for ye are the temple of the living God; as God hath said, I will dwell in them, and walk in them; and I will be their God, and they shall be my people.', 'Wherefore come out from among them, and be ye separate, saith the Lord, and touch not the unclean thing; and I will receive you,', 'And will be a Father unto you, and ye shall be my sons and daughters, saith the Lord Almighty.'])

In [85]:
l,l_attn  = en(['as the unknown, and yet known; as the dead, and siehe, we live; as the gods, and not ert;', 'as the Traurigens, but all time fröhlich; as the poor, but who make many rich; as the who do nothing, and yet all have.', 'O their corinther! our mouth has risen to you, our heart is far.', "Your habt not engen space in us; but eng is's in euren heart.", 'I talk with you as with my children, that your also against me, and will also go far.', 'Ziehet not am fremden Joch with the ungläubigen. For what has the justice to create with the injustice? What has the light for the Community with the Finsternis?', 'How does Christ obey with Belial? Or what for a part has the God with the Ungläubigen?', 'What has the temple of God for equality with the gods? Your but the temple of the living God; as God says: "I will living under them and under them... and will their God, and they will my people.', 'Therefore het from them and sonder you ab, he speaks theHER, and does not touch an unreine, so I will take you.', 'and your father be, and her shall be my son and techter, spricht the all-mighty HERR."'])

In [86]:
pred = p.cuda()
pred_attn = p_attn.cuda()
label =l.cuda()
label_attn = l_attn.cuda()

In [90]:
a = (model(label,label_attn)-model(pred,pred_attn))
a.sum()


tensor(0.5967, device='cuda:0', grad_fn=<SumBackward0>)

In [10]:
label,label_attn  = en(['I have some sympathy with the last speaker: sometimes the Committee on Budgetary Control gets so involved with the important work they are doing, that they are unable to see the wood for the trees.', 'I also welcome the presentation on behalf of the Legal Affairs Committee and the Economic and Monetary Affairs Committee which took a balanced approach to the major and indeed legitimate concerns of the Committee on Budgetary Control about fraud.'])

In [ ]:
model(pred,pred_attn)

In [1]:
import torch

In [29]:
inpu = torch.rand(1,requires_grad=False)
inpu
inpuB = torch.rand(1,requires_grad=False)
inpuB

tensor([0.8662])

In [30]:
W = torch.rand(1,requires_grad=True)
W
print(W)

tensor([0.9243], requires_grad=True)


In [31]:
output = W*inpu + inpuB

In [32]:
torch.autograd.grad(outputs=output, inputs=inpu,create_graph=True, retain_graph=True, only_inputs=True)

RuntimeError: One of the differentiated Tensors does not require grad

In [39]:

alpha = torch.rand((5, 1, 1),device=torch.device('cuda:0'))
onehot_real = torch.ones(5,4,3)
alpha = alpha.expand(onehot_real.size())

In [41]:
a = torch.ones(3,2,3)
b = torch.ones(3,4,3)

In [42]:
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [43]:
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [47]:
torch.sum(a,b)

TypeError: sum() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [40]:
d([[ 7272,   266,     7,   229,  8330,    10,  8262,  1301,   558,    16,
           74,     3, 30604,    29,  3545,   170,   645, 23072,    35,  7510,
          425,  4714,     6,     3, 20740,    74,   781, 12319,   311,    46,
         1324,    29, 23877,     6,     3,    49,   510,   860,    60,   155,
           15,    17,   680,     5,     1]])

['Denn eines ist klar: Selbst wenn wir in der Europäischen Union zu einer ausgezeichneten Regelung kommen, hört der Verkehr nicht an unseren Grenzen, er überschreitet sie.']

In [41]:
d([[ 1674,  6509,  8301,   340, 19146,    49, 15679,    49,     6,  8816,
           29, 16608,     6,   218,  1834,  5512,   170,     3,  1878,  6973,
            3, 23020,     5,     1,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]])

['Ich möchte daher dem Berichterstatter, Herrn Koch, für seine Arbeit zu dieser Frage danken.']

In [1]:
import torch

In [59]:
gradient_penalty = torch.load('./checkpoint/gradient_penalty.pt')
gradient = torch.load('./checkpoint/gradient.pt')
interpolates = torch.load('./checkpoint/interpolates.pt')
onehot_real = torch.load('./checkpoint/onehot_real.pt')
fake = torch.load('./checkpoint/fake.pt')
output = torch.load('./checkpoint/output.pt')
real = torch.load('./checkpoint/real.pt')
fake_ = torch.load('./checkpoint/fake_.pt')
alpha = torch.load('./checkpoint/alpha.pt')

In [87]:
torch.clip(alpha, min=1e-2)

tensor([[[0.6736]],

        [[0.1732]],

        [[0.0100]],

        [[0.3951]]], device='cuda:0')

In [61]:
d([real[-2]])

['I would like, first of all, to thank the rapporteur for his exceptionally accurate and technical work on the report and, secondly, the Commission for the proposal it has submitted.']

In [62]:
d([torch.argmax(fake_[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [63]:
d([torch.argmax(fake[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [64]:
d([torch.argmax(onehot_real[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [79]:
torch.max(interpolates[-2],-1)

torch.return_types.max(
values=tensor([9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9

In [80]:
1-(interpolates[:, :,0]>1e-3).long()

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,

In [75]:
output

tensor([[0.1348],
        [0.0587],
        [0.0330],
        [0.0602]], device='cuda:0', requires_grad=True)

In [74]:
torch.max(gradient[-2],-1)

torch.return_types.max(
values=tensor([1.1048e-02, 7.9653e-03, 6.0113e-03, 5.5646e-03, 1.9542e-02, 1.3272e-02,
        7.2185e-03, 1.3174e-02, 8.0519e-03, 1.2683e-02, 4.3365e-03, 3.6778e-03,
        3.5361e-03, 3.4416e-03, 5.2472e-03, 1.0689e-02, 4.5117e-03, 5.3209e-03,
        5.8149e-03, 4.3310e-03, 1.0768e-02, 6.1060e-03, 2.5659e-03, 5.4847e-03,
        1.3335e-02, 1.1511e-02, 4.0305e-03, 3.6598e-03, 5.6789e-03, 9.4820e-03,
        1.5657e-02, 8.7381e-03, 7.0189e-03, 3.3296e-02, 7.5614e-02, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1302e+01, 2.4101e+01,
        2.0388e+01, 1.9873e+01, 2.0791e+01, 2.4457e+01, 2.1025e+01, 4.8850e+01,
        9.2354e+01, 2.7918e+01, 1.2031e+01, 1.7346e+01, 1.7141e+01, 1.1054e+01,
        1.7246e+01, 1.7372e+01, 1.8897e+01, 1.8529e+01, 1.7869e+01, 2.4627e+01,
        1.3377e+01, 1.4612e+01, 1.4314e+01, 1.5957e+01, 1.5814e+01, 1.5940e+01,
        1

In [68]:
((gradient.norm(2, dim=1) - 1) ** 2).mean(-1)[-2]

tensor(40464.6172, device='cuda:0', grad_fn=<SelectBackward0>)

In [4]:
en(['周'])

(tensor([[3, 2, 1]]), tensor([[1, 1, 1]]))

In [5]:
en(['hi'])

(tensor([[7102,    1]]), tensor([[1, 1]]))

In [7]:
en(['nidwnaidnaiwdhaiwhda'])

(tensor([[   3,   29,   23,   26,  210,   29, 6146,   29,    9,   23,  210,   26,
          1024,   23,  210,  107,   26,    9,    1]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))