In [1]:
from utils import *


In [2]:
x = [[13959,  1566,    12,  2968,    10,     1,    37,   511,  1921,    19,
            24,    13,     3,    35, 21933,    84,    56,     6,    13,   503,
             6,    43,     3,     9, 10710,  1113,     6,   321,    16,  1487,
          1208,    11, 20187,  1353,     5,     1,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [13959,  1566,    12,  2968,    10,     1,   101,   103,    59,   241,
            12,   143,     8,  1124,    13,  2259,  4131,    21,   128,  1440,
         31823,   120,    11,  1172,   135,    21,  1440,   224,    38,  9652,
            42,   119, 11811,  1440,     5,     1,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]]

In [3]:
d(x)

['translate English to German: The second challenge is that of enlargement which will, of course, have a considerable impact, both in budgetary and geographical terms.',
 'translate English to German: We do not want to make the conditions of competition worse for some countries unilaterally and improve them for countries such as Austria or other transit countries.']

In [5]:
d([[  316, 15402, 18386,  8962,    16,    74, 30346,     6,    67,  4512,
         27554,    15,     3, 27485,   219,   177,     3, 19594,    29,    64,
           873, 16407,  1779,  5728,   745,   551,     5,     1,     0,     0],
        [ 1185,  6056,   311,    67,     3, 19745,     7, 17391,   218,  4847,
         24886,   236, 13584, 10020,   109,   524,  2947,    64,   680,   218,
             3,     2, 12852,   401,  2903, 24885, 19881, 22372,     5,     1]])

['Die zweite Herausforderung besteht in der Erweiterung, die natürlich erhebliche Auswirkungen auf den wirtschaftlichen und geographischen Bereich haben wird.',
 'Wir wollen nicht die Wettbewerbsbedingungen für einige Länder einseitig verschlechtern und sie für sterreich oder andere Transitländer verbessern.']

In [6]:
d([[  316, 27932, 18386,  8962,    16,    74, 30346,     6,    67,  2662,
             3,    15,     3, 27485,   219,  1324, 21068, 17375,    29,    64,
           873, 16407,  1779,  5728,   745,   551,     5,     1,     1,   644],
        [ 1185,  6056,    67,   790,     3, 28510,     7, 17391,   219,  4847,
         24886,   236, 13584, 10020,    40,   524,  2947,    64,   680,   311,
          2903,     2, 12852,   401,  2903, 24885, 19881, 22372,     5,     1]])

['Die dritte Herausforderung besteht in der Erweiterung, die ja e Auswirkungen auf unsere Haushaltöffentlichenn und geographischen Bereich haben wird. Das',
 'Wir wollen die nur Regelnsbedingungen auf einige Länder einseitig verschlchtern und sie nicht anderesterreich oder andere Transitländer verbessern.']

In [1]:
import torch

In [5]:
model = torch.load('./model/G_AB.pt').eval()

In [9]:
pred,pred_attn  = en(['relating to establishing a framework framework for the development and development development of the European Union and the development development of the European Union and the development of the European Union and the development development of a framework framework framework for the development and development development of the European Union and the development development of a framework framework framework for the development and development development of the European Union and the development development of a framework framework framework for the development and development of the European Union and the development development of the European Union and the development of the European Union, and the development development of a reprehensible forestry.', 'relating to the issue of fraud and fraud fraud. – a report on the issue of fraud and fraud in the EU and the European Commission’s report on the issue of fraud prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention prevention.'])

In [10]:
label,label_attn  = en(['I have some sympathy with the last speaker: sometimes the Committee on Budgetary Control gets so involved with the important work they are doing, that they are unable to see the wood for the trees.', 'I also welcome the presentation on behalf of the Legal Affairs Committee and the Economic and Monetary Affairs Committee which took a balanced approach to the major and indeed legitimate concerns of the Committee on Budgetary Control about fraud.'])

In [ ]:
model(pred,pred_attn)

In [1]:
import torch

In [29]:
inpu = torch.rand(1,requires_grad=False)
inpu
inpuB = torch.rand(1,requires_grad=False)
inpuB

tensor([0.8662])

In [30]:
W = torch.rand(1,requires_grad=True)
W
print(W)

tensor([0.9243], requires_grad=True)


In [31]:
output = W*inpu + inpuB

In [32]:
torch.autograd.grad(outputs=output, inputs=inpu,create_graph=True, retain_graph=True, only_inputs=True)

RuntimeError: One of the differentiated Tensors does not require grad

In [39]:

alpha = torch.rand((5, 1, 1),device=torch.device('cuda:0'))
onehot_real = torch.ones(5,4,3)
alpha = alpha.expand(onehot_real.size())

In [41]:
a = torch.ones(3,2,3)
b = torch.ones(3,4,3)

In [42]:
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [43]:
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [47]:
torch.sum(a,b)

TypeError: sum() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [40]:
d([[ 7272,   266,     7,   229,  8330,    10,  8262,  1301,   558,    16,
           74,     3, 30604,    29,  3545,   170,   645, 23072,    35,  7510,
          425,  4714,     6,     3, 20740,    74,   781, 12319,   311,    46,
         1324,    29, 23877,     6,     3,    49,   510,   860,    60,   155,
           15,    17,   680,     5,     1]])

['Denn eines ist klar: Selbst wenn wir in der Europäischen Union zu einer ausgezeichneten Regelung kommen, hört der Verkehr nicht an unseren Grenzen, er überschreitet sie.']

In [41]:
d([[ 1674,  6509,  8301,   340, 19146,    49, 15679,    49,     6,  8816,
           29, 16608,     6,   218,  1834,  5512,   170,     3,  1878,  6973,
            3, 23020,     5,     1,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]])

['Ich möchte daher dem Berichterstatter, Herrn Koch, für seine Arbeit zu dieser Frage danken.']

In [1]:
import torch

In [59]:
gradient_penalty = torch.load('./checkpoint/gradient_penalty.pt')
gradient = torch.load('./checkpoint/gradient.pt')
interpolates = torch.load('./checkpoint/interpolates.pt')
onehot_real = torch.load('./checkpoint/onehot_real.pt')
fake = torch.load('./checkpoint/fake.pt')
output = torch.load('./checkpoint/output.pt')
real = torch.load('./checkpoint/real.pt')
fake_ = torch.load('./checkpoint/fake_.pt')
alpha = torch.load('./checkpoint/alpha.pt')

In [87]:
torch.clip(alpha, min=1e-2)

tensor([[[0.6736]],

        [[0.1732]],

        [[0.0100]],

        [[0.3951]]], device='cuda:0')

In [61]:
d([real[-2]])

['I would like, first of all, to thank the rapporteur for his exceptionally accurate and technical work on the report and, secondly, the Commission for the proposal it has submitted.']

In [62]:
d([torch.argmax(fake_[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [63]:
d([torch.argmax(fake[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [64]:
d([torch.argmax(onehot_real[-2],-1)])

['We believe that this is a question that the Commission should take account of the decisions of this Parliament, especially with regard to the mid-term review of these guidelines.']

In [79]:
torch.max(interpolates[-2],-1)

torch.return_types.max(
values=tensor([9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01, 9.9991e-01,
        9.9991e-01, 9.9991e-01, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05, 9.2154e-05,
        9

In [80]:
1-(interpolates[:, :,0]>1e-3).long()

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,

In [75]:
output

tensor([[0.1348],
        [0.0587],
        [0.0330],
        [0.0602]], device='cuda:0', requires_grad=True)

In [74]:
torch.max(gradient[-2],-1)

torch.return_types.max(
values=tensor([1.1048e-02, 7.9653e-03, 6.0113e-03, 5.5646e-03, 1.9542e-02, 1.3272e-02,
        7.2185e-03, 1.3174e-02, 8.0519e-03, 1.2683e-02, 4.3365e-03, 3.6778e-03,
        3.5361e-03, 3.4416e-03, 5.2472e-03, 1.0689e-02, 4.5117e-03, 5.3209e-03,
        5.8149e-03, 4.3310e-03, 1.0768e-02, 6.1060e-03, 2.5659e-03, 5.4847e-03,
        1.3335e-02, 1.1511e-02, 4.0305e-03, 3.6598e-03, 5.6789e-03, 9.4820e-03,
        1.5657e-02, 8.7381e-03, 7.0189e-03, 3.3296e-02, 7.5614e-02, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1302e+01, 2.4101e+01,
        2.0388e+01, 1.9873e+01, 2.0791e+01, 2.4457e+01, 2.1025e+01, 4.8850e+01,
        9.2354e+01, 2.7918e+01, 1.2031e+01, 1.7346e+01, 1.7141e+01, 1.1054e+01,
        1.7246e+01, 1.7372e+01, 1.8897e+01, 1.8529e+01, 1.7869e+01, 2.4627e+01,
        1.3377e+01, 1.4612e+01, 1.4314e+01, 1.5957e+01, 1.5814e+01, 1.5940e+01,
        1

In [68]:
((gradient.norm(2, dim=1) - 1) ** 2).mean(-1)[-2]

tensor(40464.6172, device='cuda:0', grad_fn=<SelectBackward0>)

In [4]:
en(['周'])

(tensor([[3, 2, 1]]), tensor([[1, 1, 1]]))

In [5]:
en(['hi'])

(tensor([[7102,    1]]), tensor([[1, 1]]))

In [7]:
en(['nidwnaidnaiwdhaiwhda'])

(tensor([[   3,   29,   23,   26,  210,   29, 6146,   29,    9,   23,  210,   26,
          1024,   23,  210,  107,   26,    9,    1]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))

In [ ]:

from datasets import load_dataset,load_metric
load_dataset("bible_para", lang1="de", lang2="en").shape